name: Guilder
main: org.dazzlewire.Guilder.Guilder
version: 0.0.2
description: >
             Hello World!
commands:
  guilder:
    description: Use the Guilder plugin.
  g:
<<<<<<< HEAD
    description: Use the guild-chat to chat with your friends.
=======
    description: Use the guild-chat to chat with your friends
  hej:
    description: fugl.
>>>>>>> Test
